services:
  artportfolio.api:
    container_name: artworks.api
    image: artportfolio.api
    build:
      context: .
      dockerfile: ArtPortfolio.API/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - artwork-network
  
  mongodb:
    image: mongo
    container_name: artworks.db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "Artworks"
      MONGO_INITDB_ROOT_USERNAME: "Artworks"
      MONGO_INITDB_ROOT_PASSWORD: "123"
    networks:
      - artwork-network
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "Artworks"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "123"
    networks:
      - artwork-network

networks:
  artwork-network: